"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.OPConsultationNote = exports.documentStatusArrey = exports.documentDocStatusArrey = exports.DocumentReference = exports.Composition = exports.compositionStatusArrey = exports.DocumentBundle = exports.AppointmentActorStatusArray = exports.AppointmentStatusArray = exports.Appointment = exports.AllergyIntolerance = exports.verificationStatusArray = exports.allergyStatusArray = exports.Procedure = exports.Condition = exports.EncounterClassArray = exports.EncounterStatusArray = exports.EncounterHospitalizationDischargeDispositionArray = exports.EncounterResource = exports.Practitioner = exports.PractitionerResource = exports.Organization = exports.OrganizationResource = exports.Patient = exports.PatientResource = exports.resourceTypeArray = exports.GcpFhirSearch = exports.GcpFhirCRUD = void 0;
const gcp_1 = __importDefault(require("./classess/gcp"));
exports.GcpFhirCRUD = gcp_1.default;
const gcpSearch_1 = __importDefault(require("./classess/gcpSearch"));
exports.GcpFhirSearch = gcpSearch_1.default;
const Patient_1 = require("./resources/Patient");
Object.defineProperty(exports, "PatientResource", { enumerable: true, get: function () { return Patient_1.PatientResource; } });
Object.defineProperty(exports, "Patient", { enumerable: true, get: function () { return Patient_1.Patient; } });
const Practitioner_1 = require("./resources/Practitioner");
Object.defineProperty(exports, "PractitionerResource", { enumerable: true, get: function () { return Practitioner_1.PractitionerResource; } });
Object.defineProperty(exports, "Practitioner", { enumerable: true, get: function () { return Practitioner_1.Practitioner; } });
const Organization_1 = require("./resources/Organization");
Object.defineProperty(exports, "OrganizationResource", { enumerable: true, get: function () { return Organization_1.OrganizationResource; } });
Object.defineProperty(exports, "Organization", { enumerable: true, get: function () { return Organization_1.Organization; } });
const Encounter_1 = require("./resources/Encounter");
Object.defineProperty(exports, "EncounterResource", { enumerable: true, get: function () { return Encounter_1.EncounterResource; } });
Object.defineProperty(exports, "EncounterHospitalizationDischargeDispositionArray", { enumerable: true, get: function () { return Encounter_1.EncounterHospitalizationDischargeDispositionArray; } });
Object.defineProperty(exports, "EncounterStatusArray", { enumerable: true, get: function () { return Encounter_1.EncounterStatusArray; } });
Object.defineProperty(exports, "EncounterClassArray", { enumerable: true, get: function () { return Encounter_1.EncounterClassArray; } });
const config_1 = require("./config");
Object.defineProperty(exports, "resourceTypeArray", { enumerable: true, get: function () { return config_1.resourceTypeArray; } });
const Condition_1 = require("./resources/observations/Condition");
Object.defineProperty(exports, "Condition", { enumerable: true, get: function () { return Condition_1.Condition; } });
const Procedure_1 = require("./resources/observations/Procedure");
Object.defineProperty(exports, "Procedure", { enumerable: true, get: function () { return Procedure_1.Procedure; } });
const AllergyIntolerance_1 = require("./resources/observations/AllergyIntolerance");
Object.defineProperty(exports, "allergyStatusArray", { enumerable: true, get: function () { return AllergyIntolerance_1.allergyStatusArray; } });
Object.defineProperty(exports, "verificationStatusArray", { enumerable: true, get: function () { return AllergyIntolerance_1.verificationStatusArray; } });
Object.defineProperty(exports, "AllergyIntolerance", { enumerable: true, get: function () { return AllergyIntolerance_1.AllergyIntolerance; } });
const Appointment_1 = require("./resources/observations/Appointment");
Object.defineProperty(exports, "Appointment", { enumerable: true, get: function () { return Appointment_1.Appointment; } });
Object.defineProperty(exports, "AppointmentStatusArray", { enumerable: true, get: function () { return Appointment_1.AppointmentStatusArray; } });
Object.defineProperty(exports, "AppointmentActorStatusArray", { enumerable: true, get: function () { return Appointment_1.AppointmentActorStatusArray; } });
const DocumentBundle_1 = require("./resources/DocumentBundle");
Object.defineProperty(exports, "DocumentBundle", { enumerable: true, get: function () { return DocumentBundle_1.DocumentBundle; } });
const Composition_1 = require("./resources/observations/Composition");
Object.defineProperty(exports, "compositionStatusArrey", { enumerable: true, get: function () { return Composition_1.compositionStatusArrey; } });
Object.defineProperty(exports, "Composition", { enumerable: true, get: function () { return Composition_1.Composition; } });
const DocumentReference_1 = require("./resources/observations/DocumentReference");
Object.defineProperty(exports, "DocumentReference", { enumerable: true, get: function () { return DocumentReference_1.DocumentReference; } });
Object.defineProperty(exports, "documentDocStatusArrey", { enumerable: true, get: function () { return DocumentReference_1.documentDocStatusArrey; } });
Object.defineProperty(exports, "documentStatusArrey", { enumerable: true, get: function () { return DocumentReference_1.documentStatusArrey; } });
const Bundle_1 = require("./compositions/Bundle");
Object.defineProperty(exports, "OPConsultationNote", { enumerable: true, get: function () { return Bundle_1.OPConsultationNote; } });
//# sourceMappingURL=index.js.map